import type { Artwork } from './artworks';
import { CURATED_ARTWORKS } from './artworks';
import type { WeatherCondition, TimeOfDay } from '../weather/weather';

export interface HavenArtwork extends Artwork {
  weather: WeatherCondition[];
  moods: string[];
  timeOfDay: TimeOfDay[];
  isPexels?: boolean;
}

/**
 * Curated Pexels Haven Art Collection
 * High-resolution (1920px), serene photography under Pexels License.
 * Tags allow smart adaptation to local weather, time of day, and user mood.
 */
export const PEXELS_HAVEN_ARTWORKS: HavenArtwork[] = [
  {
    id: 'pexels-misty-mountain-lake',
    title: 'Hồ tĩnh lặng mờ sương ban mai',
    artist: 'Pexels / Eberhard Grossgasteiger',
    src: 'https://images.pexels.com/photos/1421903/pexels-photo-1421903.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1421903/',
    description: 'Màn sương sớm nhẹ nhàng buông trên mặt hồ xanh biếc giữa những rặng núi tĩnh lặng.',
    weather: ['fog', 'clear'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-rain-window-trees',
    title: 'Mưa rơi êm dịu bên hiên vắng',
    artist: 'Pexels / Kaique Rocha',
    src: 'https://images.pexels.com/photos/125510/pexels-photo-125510.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/125510/',
    description: 'Những giọt mưa long lanh trên ô cửa sổ, mang lại cảm giác an trú và bình yên sâu thẳm.',
    weather: ['rain', 'clouds'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['day', 'dusk', 'night'],
    isPexels: true,
  },
  {
    id: 'pexels-pine-forest-mist',
    title: 'Rừng thông bảng lảng trong sương',
    artist: 'Pexels / Johannes Plenio',
    src: 'https://images.pexels.com/photos/1428277/pexels-photo-1428277.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1428277/',
    description: 'Hàng ngàn cây thông hòa vào làn sương trắng mờ ảo giữa núi đồi sớm mai.',
    weather: ['fog', 'clouds'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-golden-ocean-sunset',
    title: 'Sóng vỗ êm đềm chiều hoàng hôn',
    artist: 'Pexels / Pok Rie',
    src: 'https://images.pexels.com/photos/157879/pexels-photo-157879.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/157879/',
    description: 'Sóng biển mềm mại đón nhận ánh nắng hoàng hôn ấm áp dát vàng bờ cát.',
    weather: ['dusk', 'clear'],
    moods: ['grateful', 'hopeful', 'peaceful'],
    timeOfDay: ['dusk'],
    isPexels: true,
  },
  {
    id: 'pexels-starry-night-sky',
    title: 'Trời đêm tĩnh mịch ngàn sao',
    artist: 'Pexels / Tobias Bjørkli',
    src: 'https://images.pexels.com/photos/1693095/pexels-photo-1693095.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1693095/',
    description: 'Dải ngân hà rực rỡ trong sự tĩnh lặng vô tận của màn đêm bao la.',
    weather: ['night', 'clear'],
    moods: ['reflective', 'calm', 'peaceful'],
    timeOfDay: ['night'],
    isPexels: true,
  },
  {
    id: 'pexels-sunbeams-forest',
    title: 'Tia nắng mai xuyên qua kẽ lá',
    artist: 'Pexels / Sebastian Voortman',
    src: 'https://images.pexels.com/photos/21492/pexels-photo-21492.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/21492/',
    description: 'Từng vạt nắng mai xuyên qua tán rừng sương sớm, mang đến năng lượng tươi mới và hy vọng.',
    weather: ['clear', 'fog'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-lake-mirror-reflection',
    title: 'Gương hồ soi bóng mây trời',
    artist: 'Pexels / Luca Bravo',
    src: 'https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/417074/',
    description: 'Mặt nước phẳng lặng như gương phản chiếu bầu trời quang đãng và núi xanh ngắt.',
    weather: ['clear', 'clouds'],
    moods: ['peaceful', 'calm'],
    timeOfDay: ['day'],
    isPexels: true,
  },
  {
    id: 'pexels-rain-green-hills',
    title: 'Mưa phùn vương đồi xanh ngát',
    artist: 'Pexels / Quang Nguyen Vinh',
    src: 'https://images.pexels.com/photos/2132180/pexels-photo-2132180.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/2132180/',
    description: 'Đồi chè xanh mướt tắm mình trong làn mưa dịu dàng và sương khói mờ ảo.',
    weather: ['rain', 'fog', 'clouds'],
    moods: ['calm', 'reflective'],
    timeOfDay: ['day', 'dawn'],
    isPexels: true,
  },
  {
    id: 'pexels-pier-sunset-tranquil',
    title: 'Cầu gỗ đón ánh ráng chiều',
    artist: 'Pexels / Pok Rie',
    src: 'https://images.pexels.com/photos/132037/pexels-photo-132037.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/132037/',
    description: 'Chiếc cầu gỗ mộc mạc vươn ra mặt nước bình lặng trong buổi chiều tà rực rỡ sắc cam.',
    weather: ['dusk', 'clear'],
    moods: ['reflective', 'peaceful'],
    timeOfDay: ['dusk'],
    isPexels: true,
  },
  {
    id: 'pexels-moonlight-still-water',
    title: 'Ánh trăng dịu êm trên sóng nước',
    artist: 'Pexels / Felix Mittermeier',
    src: 'https://images.pexels.com/photos/956999/pexels-photo-956999.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/956999/',
    description: 'Vầng trăng thanh tịnh tỏa ánh sáng vỗ về mặt biển đêm an tĩnh.',
    weather: ['night'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['night'],
    isPexels: true,
  },
  {
    id: 'pexels-wildflower-dawn-sun',
    title: 'Cánh đồng hoa sớm ngập tràn hy vọng',
    artist: 'Pexels / Valiphotos',
    src: 'https://images.pexels.com/photos/589840/pexels-photo-589840.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/589840/',
    description: 'Những đóa hoa dại đón ánh bình minh, khơi dậy niềm tin yêu và cảm giác biết ơn cuộc sống.',
    weather: ['clear'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-zen-bamboo-grove',
    title: 'Rừng trúc xanh an nhiên',
    artist: 'Pexels / Tom Fisk',
    src: 'https://images.pexels.com/photos/2166559/pexels-photo-2166559.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/2166559/',
    description: 'Lối đi mộc mạc giữa rừng trúc cao vút, không gian thiền định thuần khiết.',
    weather: ['clear', 'clouds', 'fog'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['day'],
    isPexels: true,
  },
  {
    id: 'pexels-cloud-sea-mountain',
    title: 'Biển mây bồng bềnh miền non cao',
    artist: 'Pexels / Simon Berger',
    src: 'https://images.pexels.com/photos/1323550/pexels-photo-1323550.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1323550/',
    description: 'Biển mây trắng xóa trôi lững lờ trên những rặng núi cao dưới bầu trời xanh bao la.',
    weather: ['clouds', 'fog'],
    moods: ['reflective', 'peaceful', 'hopeful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-autumn-forest-stream',
    title: 'Dòng suối êm trôi mùa lá thu',
    artist: 'Pexels / James Wheeler',
    src: 'https://images.pexels.com/photos/1534057/pexels-photo-1534057.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1534057/',
    description: 'Làn nước suối trong vắt róc rách luồn qua những tảng đá rêu phong giữa sắc thu rực rỡ.',
    weather: ['clear', 'clouds'],
    moods: ['grateful', 'calm', 'peaceful'],
    timeOfDay: ['day'],
    isPexels: true,
  },
  {
    id: 'pexels-winter-snow-silence',
    title: 'Tuyết trắng bao phủ không gian tĩnh lặng',
    artist: 'Pexels / Pixabay',
    src: 'https://images.pexels.com/photos/60597/pexels-photo-60597.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/60597/',
    description: 'Cành cây đọng tuyết trắng ngần trong bầu không khí trong trẻo, tịch mịch mùa đông.',
    weather: ['snow', 'clouds'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-rainy-night-bokeh',
    title: 'Ánh đèn phố đêm trong mưa dịu',
    artist: 'Pexels / Aleksandr Neplokhov',
    src: 'https://images.pexels.com/photos/1198507/pexels-photo-1198507.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1198507/',
    description: 'Ánh đèn vàng lung linh qua làn mưa đêm, tạo nên một góc ấm áp để suy ngẫm.',
    weather: ['rain', 'night'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['night'],
    isPexels: true,
  },
  {
    id: 'pexels-zen-lotus-pond',
    title: 'Bông sen thanh tịnh giữa hồ an yên',
    artist: 'Pexels / Hong Nguyen',
    src: 'https://images.pexels.com/photos/209065/pexels-photo-209065.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/209065/',
    description: 'Đóa sen hồng tao nhã vươn lên giữa tán lá xanh ngọc, biểu tượng của sự thuần khiết.',
    weather: ['clear', 'clouds', 'rain'],
    moods: ['peaceful', 'calm', 'grateful'],
    timeOfDay: ['day', 'dawn'],
    isPexels: true,
  },
  {
    id: 'pexels-pastel-dusk-horizon',
    title: 'Ráng chiều dịu ngọt chân trời',
    artist: 'Pexels / Billel Moula',
    src: 'https://images.pexels.com/photos/534164/pexels-photo-534164.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/534164/',
    description: 'Dải màu pastel hồng tím mềm mại chuyển dần sang đêm muộn nơi cuối chân trời.',
    weather: ['dusk'],
    moods: ['reflective', 'grateful'],
    timeOfDay: ['dusk'],
    isPexels: true,
  },
  {
    id: 'pexels-aurora-borealis-fjord',
    title: 'Cực quang huyền ảo soi bóng vịnh băng',
    artist: 'Pexels / Stein Egil Liland',
    src: 'https://images.pexels.com/photos/1933239/pexels-photo-1933239.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1933239/',
    description: 'Dải cực quang xanh ngọc nhảy múa trên bầu trời đêm bắc cực soi bóng nước phẳng lặng.',
    weather: ['night', 'clear'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['night'],
    isPexels: true,
  },
  {
    id: 'pexels-lavender-dawn-fields',
    title: 'Cánh đồng hoa oải hương trong nắng mai',
    artist: 'Pexels / David Bartus',
    src: 'https://images.pexels.com/photos/1166209/pexels-photo-1166209.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1166209/',
    description: 'Màu tím biếc trải dài vô tận đón ánh bình minh ấm áp dịu dàng.',
    weather: ['clear'],
    moods: ['grateful', 'hopeful', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-kyoto-bamboo-path',
    title: 'Lối mòn rừng trúc Arashiyama tĩnh tại',
    artist: 'Pexels / Belle Co',
    src: 'https://images.pexels.com/photos/1000498/pexels-photo-1000498.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1000498/',
    description: 'Con đường tĩnh mịch xuyên qua rặng trúc xanh cao vút đón gió mát lành.',
    weather: ['fog', 'clouds', 'clear'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-cherry-blossom-canal',
    title: 'Hoa anh đào soi bóng dòng kênh mùa xuân',
    artist: 'Pexels / Bagus Pangestu',
    src: 'https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1440476/',
    description: 'Cánh hoa anh đào phớt hồng rụng rơi nhẹ nhàng trên mặt nước êm ả.',
    weather: ['clear', 'clouds'],
    moods: ['hopeful', 'peaceful', 'grateful'],
    timeOfDay: ['day', 'dawn'],
    isPexels: true,
  },
  {
    id: 'pexels-alps-emerald-lake',
    title: 'Hồ ngọc bích giữa rặng núi Alps',
    artist: 'Pexels / Bailey Zindel',
    src: 'https://images.pexels.com/photos/869258/pexels-photo-869258.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/869258/',
    description: 'Mặt nước hồ xanh ngắt như gương soi bóng rặng thông và đỉnh núi tuyết xa mờ.',
    weather: ['clear', 'fog'],
    moods: ['calm', 'peaceful', 'grateful'],
    timeOfDay: ['day', 'dawn'],
    isPexels: true,
  },
  {
    id: 'pexels-misty-waterfall-serenity',
    title: 'Dòng thác ẩn mình giữa rừng nguyên sinh',
    artist: 'Pexels / Tom Fisk',
    src: 'https://images.pexels.com/photos/1574843/pexels-photo-1574843.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1574843/',
    description: 'Làn sương nước dịu mát lan tỏa từ thác nước thanh bình giữa đại ngàn xanh ngắt.',
    weather: ['fog', 'rain', 'clouds'],
    moods: ['calm', 'reflective'],
    timeOfDay: ['day'],
    isPexels: true,
  },
  {
    id: 'pexels-sahara-sand-ripples',
    title: 'Gợn cát vàng êm đềm trên đồi sa mạc',
    artist: 'Pexels / Tobi',
    src: 'https://images.pexels.com/photos/635279/pexels-photo-635279.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/635279/',
    description: 'Đường cong uốn lượn nhịp nhàng của đồi cát mịn màng dưới ánh chiều tà ấm áp.',
    weather: ['clear', 'dusk'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['dawn', 'dusk', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-turquoise-ocean-calm',
    title: 'Làn nước ngọc lam vỗ nhẹ bờ cát trắng',
    artist: 'Pexels / Asad Photo Maldives',
    src: 'https://images.pexels.com/photos/1450360/pexels-photo-1450360.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1450360/',
    description: 'Biển êm trong vắt từng gợn sóng nhỏ rì rào nâng niu bờ cát mịn màng.',
    weather: ['clear'],
    moods: ['peaceful', 'hopeful', 'grateful'],
    timeOfDay: ['day'],
    isPexels: true,
  },
  {
    id: 'pexels-autumn-maple-pagoda',
    title: 'Rừng phong lá đỏ mùa thu trầm mặc',
    artist: 'Pexels / Susanne Jutzeler',
    src: 'https://images.pexels.com/photos/1237119/pexels-photo-1237119.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1237119/',
    description: 'Sắc lá đỏ thắm của mùa thu bao bọc lấy mái chùa cổ trong tĩnh lặng an yên.',
    weather: ['clouds', 'clear', 'dusk'],
    moods: ['reflective', 'grateful'],
    timeOfDay: ['day', 'dusk'],
    isPexels: true,
  },
  {
    id: 'pexels-zen-balancing-stones',
    title: 'Tháp đá cuội thiền định bên bờ suối vắng',
    artist: 'Pexels / Pixabay',
    src: 'https://images.pexels.com/photos/235985/pexels-photo-235985.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/235985/',
    description: 'Những viên đá cuội xếp chồng thăng bằng hoàn hảo giữa dòng nước róc rách thanh tịnh.',
    weather: ['clear', 'fog', 'clouds'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-alpine-snowy-cabin',
    title: 'Túp lều gỗ bình yên giữa rừng tuyết trắng',
    artist: 'Pexels / Simon Berger',
    src: 'https://images.pexels.com/photos/688660/pexels-photo-688660.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/688660/',
    description: 'Một góc trú ngụ ấm cúng giữa thung lũng tuyết phủ bao la mùa đông.',
    weather: ['snow', 'clouds'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['day', 'dusk'],
    isPexels: true,
  },
  {
    id: 'pexels-sunset-cloud-sea',
    title: 'Biển mây bồng bềnh đón ánh tà dương',
    artist: 'Pexels / eberhard grossgasteiger',
    src: 'https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/440731/',
    description: 'Từng lớp mây trắng cuồn cuộn dát vàng trong ánh hoàng hôn rực rỡ trên đỉnh núi cao.',
    weather: ['dusk', 'clouds'],
    moods: ['hopeful', 'grateful', 'peaceful'],
    timeOfDay: ['dusk'],
    isPexels: true,
  },
  {
    id: 'pexels-foggy-redwood-forest',
    title: 'Đại ngàn cổ thụ ẩn mình trong màn sương',
    artist: 'Pexels / Michael Block',
    src: 'https://images.pexels.com/photos/3225517/pexels-photo-3225517.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/3225517/',
    description: 'Những thân cây ngàn năm sừng sững trong sương mờ ẩm ướt của khu rừng ôn đới.',
    weather: ['fog', 'rain'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-meadow-lone-tree',
    title: 'Cây sồi cổ thụ đơn độc giữa đồng hoa cỏ',
    artist: 'Pexels / Bessi',
    src: 'https://images.pexels.com/photos/338936/pexels-photo-338936.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/338936/',
    description: 'Dáng đứng hiên ngang vững chãi giữa thảm cỏ xanh mướt trải rộng ngút ngàn.',
    weather: ['clear', 'clouds'],
    moods: ['peaceful', 'grateful'],
    timeOfDay: ['day', 'dusk'],
    isPexels: true,
  },
  {
    id: 'pexels-moonlit-forest-glade',
    title: 'Ánh trăng rọi qua vòm lá rừng u tịch',
    artist: 'Pexels / Johannes Plenio',
    src: 'https://images.pexels.com/photos/1435075/pexels-photo-1435075.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1435075/',
    description: 'Ánh trăng huyền hoặc len lỏi qua từng tán cây soi sáng lối đi trong rừng đêm.',
    weather: ['night'],
    moods: ['calm', 'reflective', 'peaceful'],
    timeOfDay: ['night'],
    isPexels: true,
  },
  {
    id: 'pexels-chamomile-morning-dew',
    title: 'Giọt sương mai đọng trên cánh cúc dại',
    artist: 'Pexels / Pixabay',
    src: 'https://images.pexels.com/photos/56866/garden-rose-red-pink-56866.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/56866/',
    description: 'Từng giọt sương trong suốt như pha lê đọng trên nhành hoa sớm, mang lại cảm giác thuần khiết.',
    weather: ['clear', 'fog'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-golden-mountain-peak',
    title: 'Đỉnh núi tuyết dát vàng trong rạng đông',
    artist: 'Pexels / Kalen Emsley',
    src: 'https://images.pexels.com/photos/933054/pexels-photo-933054.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/933054/',
    description: 'Ánh nắng đầu ngày thắp sáng đỉnh núi băng giá bằng một màu vàng cam lộng lẫy.',
    weather: ['clear'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-rainy-cobblestone-street',
    title: 'Con ngõ lát đá cổ kính sau cơn mưa',
    artist: 'Pexels / Roman Odintsov',
    src: 'https://images.pexels.com/photos/4553618/pexels-photo-4553618.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/4553618/',
    description: 'Những phiến đá bóng loáng phản chiếu ánh đèn vàng ấm cúng trong buổi chiều mưa rơi.',
    weather: ['rain', 'clouds'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['day', 'dusk', 'night'],
    isPexels: true,
  },
  {
    id: 'pexels-misty-river-fjord',
    title: 'Vịnh hẹp mờ sương phản chiếu bóng mây',
    artist: 'Pexels / David Mark',
    src: 'https://images.pexels.com/photos/36717/amazing-animal-beautiful-beautifull.jpg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/36717/',
    description: 'Cảnh sắc thiên nhiên hùng vĩ nhưng thanh bình giữa mặt nước phẳng lặng và mây mờ che phủ đỉnh đồi.',
    weather: ['fog', 'clouds'],
    moods: ['peaceful', 'calm'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-silent-starlit-lake',
    title: 'Mặt hồ tĩnh lặng dưới vòm trời đầy sao',
    artist: 'Pexels / S Migaj',
    src: 'https://images.pexels.com/photos/747964/pexels-photo-747964.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/747964/',
    description: 'Một túp lều nhỏ ven hồ dưới bầu trời đêm lấp lánh muôn vì tinh tú bình yên.',
    weather: ['night', 'clear'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['night'],
    isPexels: true,
  },
];

/**
 * Mapping classical masterpieces with weather and mood tags
 */
export const CLASSICAL_HAVEN_ARTWORKS: HavenArtwork[] = [
  {
    ...CURATED_ARTWORKS[0], // Hokusai Red Fuji
    weather: ['clear'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: false,
  },
  {
    ...CURATED_ARTWORKS[1], // Monet Water Lilies
    weather: ['clear', 'clouds'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['day'],
    isPexels: false,
  },
  {
    ...CURATED_ARTWORKS[2], // Hasui Lake Chūzenji
    weather: ['fog', 'clouds', 'dusk'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['dusk', 'dawn'],
    isPexels: false,
  },
  {
    ...CURATED_ARTWORKS[3], // Turner Evening Star
    weather: ['dusk', 'night'],
    moods: ['reflective', 'peaceful'],
    timeOfDay: ['dusk', 'night'],
    isPexels: false,
  },
  {
    ...CURATED_ARTWORKS[4], // Friedrich Morning Mist
    weather: ['fog', 'clear'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['dawn', 'day'],
    isPexels: false,
  },
];

/**
 * Complete collection of Haven Artworks combining dynamic Pexels photography
 * and verified classical masterpieces.
 */
export const ALL_HAVEN_ARTWORKS: HavenArtwork[] = [
  ...PEXELS_HAVEN_ARTWORKS,
  ...CLASSICAL_HAVEN_ARTWORKS,
];

export function getPexelsArtworks(): HavenArtwork[] {
  return [...PEXELS_HAVEN_ARTWORKS];
}

export function getAllHavenArtworks(): HavenArtwork[] {
  return [...ALL_HAVEN_ARTWORKS];
}
