import type { Artwork } from './artworks';
import { CURATED_ARTWORKS } from './artworks';
import type { WeatherCondition, TimeOfDay } from '../weather/weather';

export interface HavenArtwork extends Artwork {
  weather: WeatherCondition[];
  moods: string[];
  timeOfDay: TimeOfDay[];
  isPexels?: boolean;
  provider?: 'pexels' | 'unsplash' | 'pixabay' | 'wikimedia' | 'classical';
}

/**
 * Curated Pexels Haven Art Collection
 * High-resolution (1920px), serene photography under Pexels License.
 * Tags allow smart adaptation to local weather, time of day, and user mood.
 */
export const PEXELS_HAVEN_ARTWORKS: HavenArtwork[] = [
  {
    id: 'pexels-misty-mountain-lake',
    title: 'Hồ tĩnh lặng mờ sương ban mai',
    artist: 'Pexels / Eberhard Grossgasteiger',
    src: 'https://images.pexels.com/photos/1421903/pexels-photo-1421903.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1421903/',
    description: 'Màn sương sớm nhẹ nhàng buông trên mặt hồ xanh biếc giữa những rặng núi tĩnh lặng.',
    weather: ['fog', 'clear'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-rain-window-trees',
    title: 'Mưa rơi êm dịu bên hiên vắng',
    artist: 'Pexels / Kaique Rocha',
    src: 'https://images.pexels.com/photos/125510/pexels-photo-125510.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/125510/',
    description: 'Những giọt mưa long lanh trên ô cửa sổ, mang lại cảm giác an trú và bình yên sâu thẳm.',
    weather: ['rain', 'clouds'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['day', 'dusk', 'night'],
    isPexels: true,
  },
  {
    id: 'pexels-pine-forest-mist',
    title: 'Rừng thông bảng lảng trong sương',
    artist: 'Pexels / Johannes Plenio',
    src: 'https://images.pexels.com/photos/1428277/pexels-photo-1428277.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1428277/',
    description: 'Hàng ngàn cây thông hòa vào làn sương trắng mờ ảo giữa núi đồi sớm mai.',
    weather: ['fog', 'clouds'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-golden-ocean-sunset',
    title: 'Sóng vỗ êm đềm chiều hoàng hôn',
    artist: 'Pexels / Pok Rie',
    src: 'https://images.pexels.com/photos/157879/pexels-photo-157879.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/157879/',
    description: 'Sóng biển mềm mại đón nhận ánh nắng hoàng hôn ấm áp dát vàng bờ cát.',
    weather: ['dusk', 'clear'],
    moods: ['grateful', 'hopeful', 'peaceful'],
    timeOfDay: ['dusk'],
    isPexels: true,
  },
  {
    id: 'pexels-starry-night-sky',
    title: 'Trời đêm tĩnh mịch ngàn sao',
    artist: 'Pexels / Tobias Bjørkli',
    src: 'https://images.pexels.com/photos/1693095/pexels-photo-1693095.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1693095/',
    description: 'Dải ngân hà rực rỡ trong sự tĩnh lặng vô tận của màn đêm bao la.',
    weather: ['night', 'clear'],
    moods: ['reflective', 'calm', 'peaceful'],
    timeOfDay: ['night'],
    isPexels: true,
  },
  {
    id: 'pexels-sunbeams-forest',
    title: 'Tia nắng mai xuyên qua kẽ lá',
    artist: 'Pexels / Sebastian Voortman',
    src: 'https://images.pexels.com/photos/21492/pexels-photo-21492.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/21492/',
    description: 'Từng vạt nắng mai xuyên qua tán rừng sương sớm, mang đến năng lượng tươi mới và hy vọng.',
    weather: ['clear', 'fog'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-lake-mirror-reflection',
    title: 'Gương hồ soi bóng mây trời',
    artist: 'Pexels / Luca Bravo',
    src: 'https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/417074/',
    description: 'Mặt nước phẳng lặng như gương phản chiếu bầu trời quang đãng và núi xanh ngắt.',
    weather: ['clear', 'clouds'],
    moods: ['peaceful', 'calm'],
    timeOfDay: ['day'],
    isPexels: true,
  },
  {
    id: 'pexels-rain-green-hills',
    title: 'Mưa phùn vương đồi xanh ngát',
    artist: 'Pexels / Quang Nguyen Vinh',
    src: 'https://images.pexels.com/photos/2132180/pexels-photo-2132180.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/2132180/',
    description: 'Đồi chè xanh mướt tắm mình trong làn mưa dịu dàng và sương khói mờ ảo.',
    weather: ['rain', 'fog', 'clouds'],
    moods: ['calm', 'reflective'],
    timeOfDay: ['day', 'dawn'],
    isPexels: true,
  },
  {
    id: 'pexels-pier-sunset-tranquil',
    title: 'Cầu gỗ đón ánh ráng chiều',
    artist: 'Pexels / Pok Rie',
    src: 'https://images.pexels.com/photos/132037/pexels-photo-132037.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/132037/',
    description: 'Chiếc cầu gỗ mộc mạc vươn ra mặt nước bình lặng trong buổi chiều tà rực rỡ sắc cam.',
    weather: ['dusk', 'clear'],
    moods: ['reflective', 'peaceful'],
    timeOfDay: ['dusk'],
    isPexels: true,
  },
  {
    id: 'pexels-moonlight-still-water',
    title: 'Ánh trăng dịu êm trên sóng nước',
    artist: 'Pexels / Felix Mittermeier',
    src: 'https://images.pexels.com/photos/956999/pexels-photo-956999.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/956999/',
    description: 'Vầng trăng thanh tịnh tỏa ánh sáng vỗ về mặt biển đêm an tĩnh.',
    weather: ['night'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['night'],
    isPexels: true,
  },
  {
    id: 'pexels-wildflower-dawn-sun',
    title: 'Cánh đồng hoa sớm ngập tràn hy vọng',
    artist: 'Pexels / Valiphotos',
    src: 'https://images.pexels.com/photos/589840/pexels-photo-589840.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/589840/',
    description: 'Những đóa hoa dại đón ánh bình minh, khơi dậy niềm tin yêu và cảm giác biết ơn cuộc sống.',
    weather: ['clear'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-zen-bamboo-grove',
    title: 'Rừng trúc xanh an nhiên',
    artist: 'Pexels / Tom Fisk',
    src: 'https://images.pexels.com/photos/2166559/pexels-photo-2166559.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/2166559/',
    description: 'Lối đi mộc mạc giữa rừng trúc cao vút, không gian thiền định thuần khiết.',
    weather: ['clear', 'clouds', 'fog'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['day'],
    isPexels: true,
  },
  {
    id: 'pexels-cloud-sea-mountain',
    title: 'Biển mây bồng bềnh miền non cao',
    artist: 'Pexels / Simon Berger',
    src: 'https://images.pexels.com/photos/1323550/pexels-photo-1323550.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1323550/',
    description: 'Biển mây trắng xóa trôi lững lờ trên những rặng núi cao dưới bầu trời xanh bao la.',
    weather: ['clouds', 'fog'],
    moods: ['reflective', 'peaceful', 'hopeful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-autumn-forest-stream',
    title: 'Dòng suối êm trôi mùa lá thu',
    artist: 'Pexels / James Wheeler',
    src: 'https://images.pexels.com/photos/1534057/pexels-photo-1534057.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1534057/',
    description: 'Làn nước suối trong vắt róc rách luồn qua những tảng đá rêu phong giữa sắc thu rực rỡ.',
    weather: ['clear', 'clouds'],
    moods: ['grateful', 'calm', 'peaceful'],
    timeOfDay: ['day'],
    isPexels: true,
  },
  {
    id: 'pexels-winter-snow-silence',
    title: 'Tuyết trắng bao phủ không gian tĩnh lặng',
    artist: 'Pexels / Pixabay',
    src: 'https://images.pexels.com/photos/60597/pexels-photo-60597.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/60597/',
    description: 'Cành cây đọng tuyết trắng ngần trong bầu không khí trong trẻo, tịch mịch mùa đông.',
    weather: ['snow', 'clouds'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-rainy-night-bokeh',
    title: 'Ánh đèn phố đêm trong mưa dịu',
    artist: 'Pexels / Aleksandr Neplokhov',
    src: 'https://images.pexels.com/photos/1198507/pexels-photo-1198507.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1198507/',
    description: 'Ánh đèn vàng lung linh qua làn mưa đêm, tạo nên một góc ấm áp để suy ngẫm.',
    weather: ['rain', 'night'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['night'],
    isPexels: true,
  },
  {
    id: 'pexels-zen-lotus-pond',
    title: 'Bông sen thanh tịnh giữa hồ an yên',
    artist: 'Pexels / Hong Nguyen',
    src: 'https://images.pexels.com/photos/209065/pexels-photo-209065.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/209065/',
    description: 'Đóa sen hồng tao nhã vươn lên giữa tán lá xanh ngọc, biểu tượng của sự thuần khiết.',
    weather: ['clear', 'clouds', 'rain'],
    moods: ['peaceful', 'calm', 'grateful'],
    timeOfDay: ['day', 'dawn'],
    isPexels: true,
  },
  {
    id: 'pexels-pastel-dusk-horizon',
    title: 'Ráng chiều dịu ngọt chân trời',
    artist: 'Pexels / Billel Moula',
    src: 'https://images.pexels.com/photos/534164/pexels-photo-534164.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/534164/',
    description: 'Dải màu pastel hồng tím mềm mại chuyển dần sang đêm muộn nơi cuối chân trời.',
    weather: ['dusk'],
    moods: ['reflective', 'grateful'],
    timeOfDay: ['dusk'],
    isPexels: true,
  },
  {
    id: 'pexels-aurora-borealis-fjord',
    title: 'Cực quang huyền ảo soi bóng vịnh băng',
    artist: 'Pexels / Stein Egil Liland',
    src: 'https://images.pexels.com/photos/1933239/pexels-photo-1933239.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1933239/',
    description: 'Dải cực quang xanh ngọc nhảy múa trên bầu trời đêm bắc cực soi bóng nước phẳng lặng.',
    weather: ['night', 'clear'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['night'],
    isPexels: true,
  },
  {
    id: 'pexels-lavender-dawn-fields',
    title: 'Cánh đồng hoa oải hương trong nắng mai',
    artist: 'Pexels / David Bartus',
    src: 'https://images.pexels.com/photos/1166209/pexels-photo-1166209.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1166209/',
    description: 'Màu tím biếc trải dài vô tận đón ánh bình minh ấm áp dịu dàng.',
    weather: ['clear'],
    moods: ['grateful', 'hopeful', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-kyoto-bamboo-path',
    title: 'Lối mòn rừng trúc Arashiyama tĩnh tại',
    artist: 'Pexels / Belle Co',
    src: 'https://images.pexels.com/photos/1000498/pexels-photo-1000498.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1000498/',
    description: 'Con đường tĩnh mịch xuyên qua rặng trúc xanh cao vút đón gió mát lành.',
    weather: ['fog', 'clouds', 'clear'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-cherry-blossom-canal',
    title: 'Hoa anh đào soi bóng dòng kênh mùa xuân',
    artist: 'Pexels / Bagus Pangestu',
    src: 'https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1440476/',
    description: 'Cánh hoa anh đào phớt hồng rụng rơi nhẹ nhàng trên mặt nước êm ả.',
    weather: ['clear', 'clouds'],
    moods: ['hopeful', 'peaceful', 'grateful'],
    timeOfDay: ['day', 'dawn'],
    isPexels: true,
  },
  {
    id: 'pexels-alps-emerald-lake',
    title: 'Hồ ngọc bích giữa rặng núi Alps',
    artist: 'Pexels / Bailey Zindel',
    src: 'https://images.pexels.com/photos/869258/pexels-photo-869258.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/869258/',
    description: 'Mặt nước hồ xanh ngắt như gương soi bóng rặng thông và đỉnh núi tuyết xa mờ.',
    weather: ['clear', 'fog'],
    moods: ['calm', 'peaceful', 'grateful'],
    timeOfDay: ['day', 'dawn'],
    isPexels: true,
  },
  {
    id: 'pexels-misty-waterfall-serenity',
    title: 'Dòng thác ẩn mình giữa rừng nguyên sinh',
    artist: 'Pexels / Tom Fisk',
    src: 'https://images.pexels.com/photos/1574843/pexels-photo-1574843.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1574843/',
    description: 'Làn sương nước dịu mát lan tỏa từ thác nước thanh bình giữa đại ngàn xanh ngắt.',
    weather: ['fog', 'rain', 'clouds'],
    moods: ['calm', 'reflective'],
    timeOfDay: ['day'],
    isPexels: true,
  },
  {
    id: 'pexels-sahara-sand-ripples',
    title: 'Gợn cát vàng êm đềm trên đồi sa mạc',
    artist: 'Pexels / Tobi',
    src: 'https://images.pexels.com/photos/635279/pexels-photo-635279.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/635279/',
    description: 'Đường cong uốn lượn nhịp nhàng của đồi cát mịn màng dưới ánh chiều tà ấm áp.',
    weather: ['clear', 'dusk'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['dawn', 'dusk', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-turquoise-ocean-calm',
    title: 'Làn nước ngọc lam vỗ nhẹ bờ cát trắng',
    artist: 'Pexels / Asad Photo Maldives',
    src: 'https://images.pexels.com/photos/1450360/pexels-photo-1450360.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1450360/',
    description: 'Biển êm trong vắt từng gợn sóng nhỏ rì rào nâng niu bờ cát mịn màng.',
    weather: ['clear'],
    moods: ['peaceful', 'hopeful', 'grateful'],
    timeOfDay: ['day'],
    isPexels: true,
  },
  {
    id: 'pexels-autumn-maple-pagoda',
    title: 'Rừng phong lá đỏ mùa thu trầm mặc',
    artist: 'Pexels / Susanne Jutzeler',
    src: 'https://images.pexels.com/photos/1237119/pexels-photo-1237119.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1237119/',
    description: 'Sắc lá đỏ thắm của mùa thu bao bọc lấy mái chùa cổ trong tĩnh lặng an yên.',
    weather: ['clouds', 'clear', 'dusk'],
    moods: ['reflective', 'grateful'],
    timeOfDay: ['day', 'dusk'],
    isPexels: true,
  },
  {
    id: 'pexels-zen-balancing-stones',
    title: 'Tháp đá cuội thiền định bên bờ suối vắng',
    artist: 'Pexels / Pixabay',
    src: 'https://images.pexels.com/photos/235985/pexels-photo-235985.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/235985/',
    description: 'Những viên đá cuội xếp chồng thăng bằng hoàn hảo giữa dòng nước róc rách thanh tịnh.',
    weather: ['clear', 'fog', 'clouds'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-alpine-snowy-cabin',
    title: 'Túp lều gỗ bình yên giữa rừng tuyết trắng',
    artist: 'Pexels / Simon Berger',
    src: 'https://images.pexels.com/photos/688660/pexels-photo-688660.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/688660/',
    description: 'Một góc trú ngụ ấm cúng giữa thung lũng tuyết phủ bao la mùa đông.',
    weather: ['snow', 'clouds'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['day', 'dusk'],
    isPexels: true,
  },
  {
    id: 'pexels-sunset-cloud-sea',
    title: 'Biển mây bồng bềnh đón ánh tà dương',
    artist: 'Pexels / eberhard grossgasteiger',
    src: 'https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/440731/',
    description: 'Từng lớp mây trắng cuồn cuộn dát vàng trong ánh hoàng hôn rực rỡ trên đỉnh núi cao.',
    weather: ['dusk', 'clouds'],
    moods: ['hopeful', 'grateful', 'peaceful'],
    timeOfDay: ['dusk'],
    isPexels: true,
  },
  {
    id: 'pexels-foggy-redwood-forest',
    title: 'Đại ngàn cổ thụ ẩn mình trong màn sương',
    artist: 'Pexels / Michael Block',
    src: 'https://images.pexels.com/photos/3225517/pexels-photo-3225517.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/3225517/',
    description: 'Những thân cây ngàn năm sừng sững trong sương mờ ẩm ướt của khu rừng ôn đới.',
    weather: ['fog', 'rain'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-meadow-lone-tree',
    title: 'Cây sồi cổ thụ đơn độc giữa đồng hoa cỏ',
    artist: 'Pexels / Bessi',
    src: 'https://images.pexels.com/photos/338936/pexels-photo-338936.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/338936/',
    description: 'Dáng đứng hiên ngang vững chãi giữa thảm cỏ xanh mướt trải rộng ngút ngàn.',
    weather: ['clear', 'clouds'],
    moods: ['peaceful', 'grateful'],
    timeOfDay: ['day', 'dusk'],
    isPexels: true,
  },
  {
    id: 'pexels-moonlit-forest-glade',
    title: 'Ánh trăng rọi qua vòm lá rừng u tịch',
    artist: 'Pexels / Johannes Plenio',
    src: 'https://images.pexels.com/photos/1435075/pexels-photo-1435075.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/1435075/',
    description: 'Ánh trăng huyền hoặc len lỏi qua từng tán cây soi sáng lối đi trong rừng đêm.',
    weather: ['night'],
    moods: ['calm', 'reflective', 'peaceful'],
    timeOfDay: ['night'],
    isPexels: true,
  },
  {
    id: 'pexels-chamomile-morning-dew',
    title: 'Giọt sương mai đọng trên cánh cúc dại',
    artist: 'Pexels / Pixabay',
    src: 'https://images.pexels.com/photos/56866/garden-rose-red-pink-56866.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/56866/',
    description: 'Từng giọt sương trong suốt như pha lê đọng trên nhành hoa sớm, mang lại cảm giác thuần khiết.',
    weather: ['clear', 'fog'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-golden-mountain-peak',
    title: 'Đỉnh núi tuyết dát vàng trong rạng đông',
    artist: 'Pexels / Kalen Emsley',
    src: 'https://images.pexels.com/photos/933054/pexels-photo-933054.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/933054/',
    description: 'Ánh nắng đầu ngày thắp sáng đỉnh núi băng giá bằng một màu vàng cam lộng lẫy.',
    weather: ['clear'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-rainy-cobblestone-street',
    title: 'Con ngõ lát đá cổ kính sau cơn mưa',
    artist: 'Pexels / Roman Odintsov',
    src: 'https://images.pexels.com/photos/4553618/pexels-photo-4553618.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/4553618/',
    description: 'Những phiến đá bóng loáng phản chiếu ánh đèn vàng ấm cúng trong buổi chiều mưa rơi.',
    weather: ['rain', 'clouds'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['day', 'dusk', 'night'],
    isPexels: true,
  },
  {
    id: 'pexels-misty-river-fjord',
    title: 'Vịnh hẹp mờ sương phản chiếu bóng mây',
    artist: 'Pexels / David Mark',
    src: 'https://images.pexels.com/photos/36717/amazing-animal-beautiful-beautifull.jpg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/36717/',
    description: 'Cảnh sắc thiên nhiên hùng vĩ nhưng thanh bình giữa mặt nước phẳng lặng và mây mờ che phủ đỉnh đồi.',
    weather: ['fog', 'clouds'],
    moods: ['peaceful', 'calm'],
    timeOfDay: ['dawn', 'day'],
    isPexels: true,
  },
  {
    id: 'pexels-silent-starlit-lake',
    title: 'Mặt hồ tĩnh lặng dưới vòm trời đầy sao',
    artist: 'Pexels / S Migaj',
    src: 'https://images.pexels.com/photos/747964/pexels-photo-747964.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pexels License (Free to use)',
    sourceUrl: 'https://www.pexels.com/photo/747964/',
    description: 'Một túp lều nhỏ ven hồ dưới bầu trời đêm lấp lánh muôn vì tinh tú bình yên.',
    weather: ['night', 'clear'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['night'],
    isPexels: true,
  },
];

/**
 * Mapping classical masterpieces with weather and mood tags
 */
export const CLASSICAL_HAVEN_ARTWORKS: HavenArtwork[] = [
  {
    ...CURATED_ARTWORKS[0], // Hokusai Red Fuji
    weather: ['clear'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: false,
  },
  {
    ...CURATED_ARTWORKS[1], // Monet Water Lilies
    weather: ['clear', 'clouds'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['day'],
    isPexels: false,
  },
  {
    ...CURATED_ARTWORKS[2], // Hasui Lake Chūzenji
    weather: ['fog', 'clouds', 'dusk'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['dusk', 'dawn'],
    isPexels: false,
  },
  {
    ...CURATED_ARTWORKS[3], // Turner Evening Star
    weather: ['dusk', 'night'],
    moods: ['reflective', 'peaceful'],
    timeOfDay: ['dusk', 'night'],
    isPexels: false,
  },
  {
    ...CURATED_ARTWORKS[4], // Friedrich Morning Mist
    weather: ['fog', 'clear'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['dawn', 'day'],
    isPexels: false,
    provider: 'classical',
  },
];

/**
 * Curated Unsplash Haven Art Collection
 * High-resolution 1920px photography under Unsplash License.
 */
export const UNSPLASH_HAVEN_ARTWORKS: HavenArtwork[] = [
  {
    id: 'unsplash-moraine-lake-canada',
    title: 'Hồ Moraine xanh ngọc giữa rặng núi tuyết',
    artist: 'Unsplash / Luca Bravo',
    src: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/O453M2Liufs',
    description: 'Nước hồ băng xanh ngọc bích phẳng lặng soi bóng rặng núi tuyết tráng lệ tại Banff, Canada.',
    weather: ['clear', 'clouds'],
    moods: ['peaceful', 'hopeful'],
    timeOfDay: ['day', 'dawn'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-yosemite-valley-mist',
    title: 'Thung lũng Yosemite mờ sương rạng đông',
    artist: 'Unsplash / Aniket Deole',
    src: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/MDrXvhSc3cU',
    description: 'Làn sương mỏng lơ lửng giữa thung lũng đá hoa cương hùng vĩ khi ánh ban mai vừa rạng.',
    weather: ['fog', 'clear'],
    moods: ['calm', 'reflective'],
    timeOfDay: ['dawn', 'day'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-dolomites-peaks',
    title: 'Đỉnh núi Dolomites kỳ vĩ trong nắng sớm',
    artist: 'Unsplash / Ales Krivec',
    src: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/4HBUsJaDfeA',
    description: 'Những chóp núi đá Dolomites sừng sững đón ánh nắng vàng óng ả đầu ngày.',
    weather: ['clear'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-kyoto-autumn-garden',
    title: 'Khu vườn thiền Kyoto mùa lá phong đỏ',
    artist: 'Unsplash / Su San Lee',
    src: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/g95KD456vwQ',
    description: 'Khu vườn cổ kính thanh tịnh với sắc đỏ rực rỡ của lá phong mùa thu Nhật Bản.',
    weather: ['clear', 'clouds'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['day', 'dusk'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-starry-night-mountains',
    title: 'Ngàn sao lấp lánh trên đỉnh núi tuyết',
    artist: 'Unsplash / Benjamin Voros',
    src: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/phIFdC6lA4E',
    description: 'Bầu trời đêm huyền ảo vô tận với hàng triệu vì tinh tú soi rọi rặng núi tuyết.',
    weather: ['night', 'clear'],
    moods: ['reflective', 'peaceful'],
    timeOfDay: ['night'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-foggy-pine-forest',
    title: 'Làn sương bảng lảng giữa rừng thông cổ thụ',
    artist: 'Unsplash / Thomas Kelley',
    src: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/JoH60FhQA9Q',
    description: 'Sương mù trắng bao bọc thân cây thông cao vút, tạo nên vẻ đẹp tĩnh lặng như trong cổ tích.',
    weather: ['fog', 'clouds'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-norwegian-fjord',
    title: 'Vịnh hẹp Na Uy phẳng lặng như gương',
    artist: 'Unsplash / John O\'Nolan',
    src: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/60kLmTmsMBE',
    description: 'Mặt biển trong vắt soi bóng những vách đá thẳng đứng trong một buổi sáng thanh bình.',
    weather: ['clear'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['day'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-rain-glass-bokeh',
    title: 'Vệt mưa lấp lánh phản chiếu ánh đèn phố',
    artist: 'Unsplash / Max Bender',
    src: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/VmX3vmBecg4',
    description: 'Từng giọt nước mưa đọng trên cửa kính với quầng sáng bokeh ấm áp đầy hoài niệm.',
    weather: ['rain'],
    moods: ['reflective'],
    timeOfDay: ['dusk', 'night'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-lavender-field-sunset',
    title: 'Cánh đồng hoa oải hương trong ráng chiều',
    artist: 'Unsplash / Léonard Cotte',
    src: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/R5scocnOOd4',
    description: 'Những luống hoa oải hương màu tím biếc trải dài vô tận dưới ánh hoàng hôn Provence nước Pháp.',
    weather: ['dusk', 'clear'],
    moods: ['peaceful', 'grateful'],
    timeOfDay: ['dusk'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-waterfall-iceland',
    title: 'Thác nước hoang sơ giữa thảo nguyên Iceland',
    artist: 'Unsplash / Robert Bye',
    src: 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/t20UMRsl0bA',
    description: 'Dòng nước bạc tuôn trào mềm mại giữa vách đá phủ rêu xanh ngát và cây cầu gỗ mộc mạc.',
    weather: ['clouds', 'clear'],
    moods: ['calm', 'hopeful'],
    timeOfDay: ['day'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-misty-bamboo-forest',
    title: 'Rừng trúc xanh ngắt mờ sương sớm',
    artist: 'Unsplash / kazuend',
    src: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/2VsU2lUBp1k',
    description: 'Lối mòn thanh tịnh giữa ngút ngàn thân trúc xanh mướt, mang lại cảm giác an nhiên tự tại.',
    weather: ['fog', 'clear'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-sunset-pacific-ocean',
    title: 'Hoàng hôn buông rèm trên bờ biển Thái Bình Dương',
    artist: 'Unsplash / Jeremy Bishop',
    src: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/EwKXn5CapA4',
    description: 'Mặt trời đỏ rực từ từ lặn xuống biển cả, nhuộm hồng những con sóng bạc lăn tăn.',
    weather: ['dusk'],
    moods: ['peaceful', 'grateful'],
    timeOfDay: ['dusk'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-autumn-birch-forest',
    title: 'Rừng bạch dương vàng óng trong nắng thu',
    artist: 'Unsplash / Simon Berger',
    src: 'https://images.unsplash.com/photo-1476820865390-c52aeebb9891?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/twukN12EN7c',
    description: 'Thảm lá vàng rực rỡ và thân cây trắng muốt tạo nên một bức tranh mùa thu dịu dàng.',
    weather: ['clear', 'clouds'],
    moods: ['hopeful', 'calm'],
    timeOfDay: ['day'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-snowy-mountain-cabin',
    title: 'Căn nhà gỗ ấm áp giữa thung lũng tuyết trắng',
    artist: 'Unsplash / Dan Meyers',
    src: 'https://images.unsplash.com/photo-1483921020237-2ff51e8e4b22?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/-ALvl3wAD64',
    description: 'Tuyết trắng xóa bao phủ mái nhà gỗ và những rặng thông, mang hơi ấm bình an giữa mùa đông.',
    weather: ['snow'],
    moods: ['peaceful', 'calm'],
    timeOfDay: ['day', 'dusk'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-zen-stone-tower',
    title: 'Tháp đá cân bằng tĩnh lặng bên suối ngàn',
    artist: 'Unsplash / Sean Stratton',
    src: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/Y-uXbN_TjAo',
    description: 'Biểu tượng thiền định kiên cố và hài hòa giữa thiên nhiên bao la.',
    weather: ['clear'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['day'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-desert-sand-dunes',
    title: 'Những đồi cát uốn lượn dưới vầng dương hoàng hôn',
    artist: 'Unsplash / Keith Hardy',
    src: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/PpAO8n3hexg',
    description: 'Đường cong tuyệt mỹ của cát sa mạc trong ánh nắng cam ấm áp lúc chiều buông.',
    weather: ['dusk', 'clear'],
    moods: ['reflective'],
    timeOfDay: ['dusk'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-tea-plantations',
    title: 'Đồi chè xanh mướt trải dài trong làn sương',
    artist: 'Unsplash / Sreehari Devadas',
    src: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/eVqH5zU0-7A',
    description: 'Sóng chè uốn lượn xanh ngắt ngút tầm mắt trong không khí tinh khôi của sớm mai.',
    weather: ['fog', 'clear'],
    moods: ['peaceful', 'hopeful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-cloudy-alpine-pass',
    title: 'Đèo núi phủ mây trắng bồng bềnh',
    artist: 'Unsplash / Bailey Zindel',
    src: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/NRQV-hBF10M',
    description: 'Biển mây trắng lững lờ trôi qua đỉnh núi thông hùng vĩ giữa không gian bao la.',
    weather: ['clouds', 'fog'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['day'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-calm-river-reflection',
    title: 'Dòng sông êm đềm soi bóng rặng thông',
    artist: 'Unsplash / Kalen Emsley',
    src: 'https://images.unsplash.com/photo-1470246973918-29a93221c455?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/Bkci_8qcdvQ',
    description: 'Mặt sông không gợn sóng phản chiếu bầu trời xanh trong vắt và tán thông mùa hạ.',
    weather: ['clear'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['day'],
    isPexels: false,
    provider: 'unsplash',
  },
  {
    id: 'unsplash-aurora-borealis-reflection',
    title: 'Cực quang xanh nhảy múa trên mặt hồ băng',
    artist: 'Unsplash / Vincent Guth',
    src: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1920&q=80',
    license: 'Unsplash License (Free to use)',
    sourceUrl: 'https://unsplash.com/photos/52PfrS2noBE',
    description: 'Vũ điệu dải lụa xanh biếc của cực quang phương Bắc tỏa sáng bầu trời đêm huyền bí.',
    weather: ['night'],
    moods: ['hopeful', 'reflective'],
    timeOfDay: ['night'],
    isPexels: false,
    provider: 'unsplash',
  },
];

/**
 * Curated Pixabay Haven Art Collection
 * High-resolution 1920px photography under Pixabay License.
 */
export const PIXABAY_HAVEN_ARTWORKS: HavenArtwork[] = [
  {
    id: 'pixabay-lavender-field-valensole',
    title: 'Thảo nguyên hoa tím ngát hương Valensole',
    artist: 'Pixabay / Hans Braxmeier',
    src: 'https://images.pexels.com/photos/1166209/pexels-photo-1166209.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/lavender-field-flowering-plants-1166209/',
    description: 'Biển hoa oải hương tím ngát mênh mông dưới vòm trời trong vắt miền Nam nước Pháp.',
    weather: ['clear'],
    moods: ['peaceful', 'grateful'],
    timeOfDay: ['day'],
    isPexels: false,
    provider: 'pixabay',
  },
  {
    id: 'pixabay-misty-alpine-morning',
    title: 'Bình minh rạng rỡ trên rặng núi đá vôi',
    artist: 'Pixabay / Peter H',
    src: 'https://images.pexels.com/photos/167699/pexels-photo-167699.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/mountains-fog-clouds-sunrise-167699/',
    description: 'Ánh nắng mặt trời xuyên qua làn sương mù buông xuống thảo nguyên chân núi.',
    weather: ['fog', 'clear'],
    moods: ['hopeful', 'calm'],
    timeOfDay: ['dawn', 'day'],
    isPexels: false,
    provider: 'pixabay',
  },
  {
    id: 'pixabay-autumn-waterfall-stream',
    title: 'Dòng suối lá phong đỏ róc rách',
    artist: 'Pixabay / Felix Mittermeier',
    src: 'https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/waterfall-autumn-forest-nature-2387873/',
    description: 'Nước suối trong vắt len lỏi qua từng phiến đá phủ đầy lá phong vàng rực rỡ.',
    weather: ['clouds', 'clear'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['day'],
    isPexels: false,
    provider: 'pixabay',
  },
  {
    id: 'pixabay-starry-galaxy-trees',
    title: 'Dải ngân hà vắt ngang qua rặng cây cổ thụ',
    artist: 'Pixabay / Felix Mittermeier',
    src: 'https://images.pexels.com/photos/1252814/pexels-photo-1252814.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/milky-way-starry-sky-night-sky-1252814/',
    description: 'Dải Ngân Hà rực sáng với hàng triệu vì sao trên nền trời đen thẳm tịch mịch.',
    weather: ['night'],
    moods: ['reflective'],
    timeOfDay: ['night'],
    isPexels: false,
    provider: 'pixabay',
  },
  {
    id: 'pixabay-fuji-cherry-blossom',
    title: 'Núi Phú Sĩ và hoa anh đào nở rộ trong sương mai',
    artist: 'Pixabay / Kanenori',
    src: 'https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/mount-fuji-cherry-blossoms-japan-1440476/',
    description: 'Đỉnh núi tuyết trắng kiêu hãnh ẩn hiện sau những chùm hoa anh đào hồng phấn tao nhã.',
    weather: ['clear'],
    moods: ['grateful', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: false,
    provider: 'pixabay',
  },
  {
    id: 'pixabay-emerald-forest-creek',
    title: 'Suối rừng nguyên sinh trong vắt',
    artist: 'Pixabay / Walkerssk',
    src: 'https://images.pexels.com/photos/158063/bellingrath-gardens-alabama-landscape-scenic-158063.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/garden-nature-forest-stream-158063/',
    description: 'Không gian xanh ngát tĩnh mịch của cánh rừng với tiếng nước róc rách vỗ về tâm hồn.',
    weather: ['clear', 'fog'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['day'],
    isPexels: false,
    provider: 'pixabay',
  },
  {
    id: 'pixabay-norway-reine-fjord',
    title: 'Làng chài Reine yên ả bên vịnh tuyết Na Uy',
    artist: 'Pixabay / Julius Silver',
    src: 'https://images.pexels.com/photos/1525041/pexels-photo-1525041.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/reine-lofoten-norway-fishing-village-1525041/',
    description: 'Những ngôi nhà gỗ đỏ truyền thống nép mình bên mặt nước xanh ngọc và rặng núi tuyết.',
    weather: ['clear', 'snow'],
    moods: ['peaceful', 'reflective'],
    timeOfDay: ['day'],
    isPexels: false,
    provider: 'pixabay',
  },
  {
    id: 'pixabay-dune-sunset-golden',
    title: 'Đồi cát sa mạc lượn sóng trong ánh chiều tà',
    artist: 'Pixabay / Gerhard Bögner',
    src: 'https://images.pexels.com/photos/1001435/pexels-photo-1001435.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/sand-dunes-desert-sunset-1001435/',
    description: 'Cát vàng óng ả đổ bóng dài khi ánh mặt trời buông xuống nơi chân trời cát trắng.',
    weather: ['dusk', 'clear'],
    moods: ['reflective'],
    timeOfDay: ['dusk'],
    isPexels: false,
    provider: 'pixabay',
  },
  {
    id: 'pixabay-peaceful-meadow-sunrise',
    title: 'Cỏ hoa đẫm sương sớm bên cánh đồng quê',
    artist: 'Pixabay / Pezibear',
    src: 'https://images.pexels.com/photos/414102/pexels-photo-414102.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/meadow-grass-dew-drops-morning-414102/',
    description: 'Từng giọt sương mai đọng trên cánh hoa dại ngập tràn ánh nắng ban mai tinh khôi.',
    weather: ['clear'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: false,
    provider: 'pixabay',
  },
  {
    id: 'pixabay-winter-frozen-lake',
    title: 'Mặt hồ băng giá tĩnh lặng như gương mùa đông',
    artist: 'Pixabay / Simon',
    src: 'https://images.pexels.com/photos/688660/pexels-photo-688660.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/winter-frozen-lake-snow-landscape-688660/',
    description: 'Không gian tĩnh lặng tuyệt đối khi vạn vật ngủ yên dưới lớp băng tuyết mùa đông.',
    weather: ['snow'],
    moods: ['reflective', 'peaceful'],
    timeOfDay: ['day', 'dusk'],
    isPexels: false,
    provider: 'pixabay',
  },
  {
    id: 'pixabay-rain-window-evening',
    title: 'Mưa đêm nhẹ rơi trên khung cửa sổ ấm cúng',
    artist: 'Pixabay / Larisa-K',
    src: 'https://images.pexels.com/photos/21492/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/rain-drops-window-water-evening-21492/',
    description: 'Những hạt mưa tí tách bên ngoài ô cửa mang lại cảm giác bình yên và ấm cúng.',
    weather: ['rain'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['dusk', 'night'],
    isPexels: false,
    provider: 'pixabay',
  },
  {
    id: 'pixabay-bamboo-path-kyoto',
    title: 'Lối mòn trúc xanh thanh tịnh',
    artist: 'Pixabay / Michelle Raponi',
    src: 'https://images.pexels.com/photos/132037/pexels-photo-132037.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/bamboo-forest-kyoto-japan-path-132037/',
    description: 'Tiếng lá trúc xào xạc trong gió dẫn lối tâm trí về miền thanh tịnh an hòa.',
    weather: ['clear', 'fog'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['day'],
    isPexels: false,
    provider: 'pixabay',
  },
  {
    id: 'pixabay-sunset-reflection-clouds',
    title: 'Hoàng hôn dát vàng vòm trời và mặt nước',
    artist: 'Pixabay / Bessi',
    src: 'https://images.pexels.com/photos/2088170/pexels-photo-2088170.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/sunset-clouds-sky-water-reflection-2088170/',
    description: 'Bầu trời rực sáng sắc vàng cam rực rỡ phản chiếu lung linh trên mặt hồ chiều.',
    weather: ['dusk'],
    moods: ['grateful', 'peaceful'],
    timeOfDay: ['dusk'],
    isPexels: false,
    provider: 'pixabay',
  },
  {
    id: 'pixabay-misty-valley-morning',
    title: 'Thung lũng mờ ảo trong biển mây bồng bềnh',
    artist: 'Pixabay / Valiphotos',
    src: 'https://images.pexels.com/photos/167698/pexels-photo-167698.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/mountains-fog-sea-of-clouds-morning-167698/',
    description: 'Đứng trên đỉnh núi cao ngắm nhìn từng đợt mây trắng bồng bềnh như sóng biển.',
    weather: ['fog', 'clouds'],
    moods: ['calm', 'hopeful'],
    timeOfDay: ['dawn', 'day'],
    isPexels: false,
    provider: 'pixabay',
  },
  {
    id: 'pixabay-zen-stones-balance',
    title: 'Tháp đá thiền định bên làn nước trong xanh',
    artist: 'Pixabay / Benjamin Balazs',
    src: 'https://images.pexels.com/photos/312839/pexels-photo-312839.jpeg?auto=compress&cs=tinysrgb&w=1920',
    license: 'Pixabay License (Free for commercial use)',
    sourceUrl: 'https://pixabay.com/photos/stones-zen-balance-water-lake-312839/',
    description: 'Các viên sỏi cuội tròn nhẵn xếp chồng lên nhau trong trạng thái cân bằng tuyệt đối.',
    weather: ['clear'],
    moods: ['calm', 'peaceful'],
    timeOfDay: ['day'],
    isPexels: false,
    provider: 'pixabay',
  },
];

/**
 * Complete collection of Haven Artworks combining dynamic Pexels, Unsplash, Pixabay
 * and verified classical masterpieces.
 */
export const ALL_HAVEN_ARTWORKS: HavenArtwork[] = [
  ...PEXELS_HAVEN_ARTWORKS,
  ...UNSPLASH_HAVEN_ARTWORKS,
  ...PIXABAY_HAVEN_ARTWORKS,
  ...CLASSICAL_HAVEN_ARTWORKS,
];

export function getPexelsArtworks(): HavenArtwork[] {
  return [...PEXELS_HAVEN_ARTWORKS];
}

export function getUnsplashArtworks(): HavenArtwork[] {
  return [...UNSPLASH_HAVEN_ARTWORKS];
}

export function getPixabayArtworks(): HavenArtwork[] {
  return [...PIXABAY_HAVEN_ARTWORKS];
}

export function getAllHavenArtworks(): HavenArtwork[] {
  return [...ALL_HAVEN_ARTWORKS];
}
