#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../../../../');
const distDir = path.join(rootDir, 'dist/client');
const publicDir = path.join(rootDir, 'public');

console.log('🔍 [Haven Art SEO Audit Engine] Running automated SEO health check...\n');

const results = [];

function check(category, testName, status, details) {
  results.push({ category, testName, status, details });
}

// 1. Robots.txt Check
const robotsPath = fs.existsSync(path.join(distDir, 'robots.txt'))
  ? path.join(distDir, 'robots.txt')
  : path.join(publicDir, 'robots.txt');

if (fs.existsSync(robotsPath)) {
  const robotsContent = fs.readFileSync(robotsPath, 'utf8');
  if (robotsContent.includes('Sitemap:')) {
    check('Crawling & Indexing', 'robots.txt validity', 'PASS', 'File exists and includes Sitemap directive');
  } else {
    check('Crawling & Indexing', 'robots.txt validity', 'WARN', 'File exists but missing Sitemap directive');
  }
} else {
  check('Crawling & Indexing', 'robots.txt validity', 'FAIL', 'robots.txt not found');
}

// 2. Sitemap Check
const sitemapIndexPath = path.join(distDir, 'sitemap-index.xml');
const sitemap0Path = path.join(distDir, 'sitemap-0.xml');

if (fs.existsSync(sitemapIndexPath)) {
  check('Crawling & Indexing', 'sitemap-index.xml', 'PASS', 'sitemap-index.xml exists and generated by @astrojs/sitemap');
} else {
  check('Crawling & Indexing', 'sitemap-index.xml', 'WARN', 'sitemap-index.xml not found in dist/client (run npm run build first)');
}

if (fs.existsSync(sitemap0Path)) {
  const content = fs.readFileSync(sitemap0Path, 'utf8');
  if (content.includes('https://havenart.space/')) {
    check('Crawling & Indexing', 'sitemap URLs', 'PASS', 'Root URL is listed in sitemap-0.xml');
  } else {
    check('Crawling & Indexing', 'sitemap URLs', 'WARN', 'Root URL missing in sitemap');
  }
  if (!content.includes('/admin')) {
    check('Crawling & Indexing', 'sitemap private exclusions', 'PASS', '/admin route correctly excluded from public sitemap');
  } else {
    check('Crawling & Indexing', 'sitemap private exclusions', 'FAIL', '/admin route leaked into sitemap');
  }
}

// 3. HTML Metadata & OpenGraph Check (index.html)
const indexHtmlPath = path.join(distDir, 'index.html');
if (fs.existsSync(indexHtmlPath)) {
  const html = fs.readFileSync(indexHtmlPath, 'utf8');

  // Title tag
  const titleMatch = html.match(/<title>([^<]+)<\/title>/i);
  if (titleMatch) {
    const title = titleMatch[1].trim();
    if (title.length >= 20 && title.length <= 70) {
      check('On-Page SEO', 'Title Tag', 'PASS', `Length: ${title.length} chars ("${title}")`);
    } else {
      check('On-Page SEO', 'Title Tag', 'WARN', `Length: ${title.length} chars (Recommended: 30-65 chars)`);
    }
  } else {
    check('On-Page SEO', 'Title Tag', 'FAIL', '<title> tag missing');
  }

  // Meta Description
  const descMatch = html.match(/<meta\s+name=["']description["']\s+content=["']([^"']+)["']/i);
  if (descMatch) {
    const desc = descMatch[1].trim();
    if (desc.length >= 50 && desc.length <= 180) {
      check('On-Page SEO', 'Meta Description', 'PASS', `Length: ${desc.length} chars`);
    } else {
      check('On-Page SEO', 'Meta Description', 'WARN', `Length: ${desc.length} chars (Recommended: 120-160 chars)`);
    }
  } else {
    check('On-Page SEO', 'Meta Description', 'FAIL', '<meta name="description"> missing');
  }

  // Canonical Link
  const canonMatch = html.match(/<link\s+rel=["']canonical["']\s+href=["']([^"']+)["']/i);
  if (canonMatch && canonMatch[1].startsWith('https://')) {
    check('On-Page SEO', 'Canonical URL', 'PASS', `Canonical points to ${canonMatch[1]}`);
  } else {
    check('On-Page SEO', 'Canonical URL', 'FAIL', 'Canonical URL missing or not HTTPS');
  }

  // Open Graph
  const ogTitle = /<meta\s+property=["']og:title["']/i.test(html);
  const ogDesc = /<meta\s+property=["']og:description["']/i.test(html);
  const ogImage = /<meta\s+property=["']og:image["']/i.test(html);
  const ogUrl = /<meta\s+property=["']og:url["']/i.test(html);
  if (ogTitle && ogDesc && ogImage && ogUrl) {
    check('Social Meta (OG)', 'Open Graph Tags', 'PASS', 'og:title, og:description, og:image, og:url present');
  } else {
    check('Social Meta (OG)', 'Open Graph Tags', 'FAIL', 'Incomplete Open Graph tags');
  }

  // Twitter Card
  const twCard = /<meta\s+name=["']twitter:card["']/i.test(html);
  const twImage = /<meta\s+name=["']twitter:image["']/i.test(html);
  if (twCard && twImage) {
    check('Social Meta (Twitter)', 'Twitter Card Tags', 'PASS', 'twitter:card and twitter:image present');
  } else {
    check('Social Meta (Twitter)', 'Twitter Card Tags', 'FAIL', 'Incomplete Twitter Card tags');
  }

  // Schema.org JSON-LD
  const jsonLdMatches = html.match(/<script\s+type=["']application\/ld\+json["']>([^<]+)<\/script>/gi);
  if (jsonLdMatches && jsonLdMatches.length >= 2) {
    check('Structured Data', 'JSON-LD Schema.org', 'PASS', `${jsonLdMatches.length} Schema.org entities detected (WebSite & WebApplication)`);
  } else if (jsonLdMatches) {
    check('Structured Data', 'JSON-LD Schema.org', 'PASS', `${jsonLdMatches.length} Schema.org entity detected`);
  } else {
    check('Structured Data', 'JSON-LD Schema.org', 'FAIL', 'No JSON-LD structured data found');
  }

  // Alternate Hreflang
  const hreflangVi = /<link\s+rel=["']alternate["']\s+hreflang=["']vi["']/i.test(html);
  const hreflangEn = /<link\s+rel=["']alternate["']\s+hreflang=["']en["']/i.test(html);
  if (hreflangVi && hreflangEn) {
    check('International SEO', 'Hreflang tags', 'PASS', 'Multilingual hreflang (vi, en, x-default) detected');
  } else {
    check('International SEO', 'Hreflang tags', 'WARN', 'Missing alternate hreflang tags');
  }

  // Viewport & Charset
  const viewport = /<meta\s+name=["']viewport["']/i.test(html);
  const charset = /<meta\s+charset=/i.test(html);
  if (viewport && charset) {
    check('Technical SEO', 'Mobile Viewport & Charset', 'PASS', 'Responsive viewport and UTF-8 charset configured');
  } else {
    check('Technical SEO', 'Mobile Viewport & Charset', 'FAIL', 'Missing viewport or charset');
  }
} else {
  check('On-Page SEO', 'index.html', 'WARN', 'dist/client/index.html not found. Run npm run build first.');
}

// 4. Admin page noindex check
const adminHtmlPath = path.join(distDir, 'admin/index.html');
if (fs.existsSync(adminHtmlPath)) {
  const adminHtml = fs.readFileSync(adminHtmlPath, 'utf8');
  if (adminHtml.includes('noindex')) {
    check('Security & Crawling', 'Admin Noindex Protection', 'PASS', 'Admin dashboard is protected with noindex tag');
  } else {
    check('Security & Crawling', 'Admin Noindex Protection', 'FAIL', 'Admin dashboard is missing noindex meta tag!');
  }
}

// Print results table
console.log('---------------------------------------------------------------------------------------------------------');
console.log(
  'CATEGORY'.padEnd(25) +
  'TEST NAME'.padEnd(30) +
  'STATUS'.padEnd(10) +
  'DETAILS'
);
console.log('---------------------------------------------------------------------------------------------------------');

let passed = 0;
let warnings = 0;
let failures = 0;

for (const r of results) {
  let statusSymbol = r.status === 'PASS' ? '✅ PASS' : r.status === 'WARN' ? '⚠️ WARN' : '❌ FAIL';
  if (r.status === 'PASS') passed++;
  if (r.status === 'WARN') warnings++;
  if (r.status === 'FAIL') failures++;

  console.log(
    r.category.padEnd(25) +
    r.testName.padEnd(30) +
    statusSymbol.padEnd(10) +
    r.details
  );
}

console.log('---------------------------------------------------------------------------------------------------------');
console.log(`\n📊 Audit Summary: ${passed} Passed, ${warnings} Warnings, ${failures} Failures.`);
const score = Math.round((passed / results.length) * 100);
console.log(`🏆 SEO Health Score: ${score}/100\n`);

if (failures > 0) {
  process.exit(1);
} else {
  process.exit(0);
}
