import type { AudioTrack } from './tracks';
import { DEFAULT_TRACKS } from './tracks';
import type { WeatherCondition, TimeOfDay } from '../weather/weather';

export interface HavenAudioTrack extends AudioTrack {
  weather: WeatherCondition[];
  moods: string[];
  timeOfDay: TimeOfDay[];
  genreVi: string;
  category: 'piano' | 'ambient';
}

/**
 * Curated Haven Art Ambient & Classical Piano Catalog
 * Expanded collection of serene ambient soundscapes and soulful acoustic piano masterpieces.
 */
export const ALL_HAVEN_AUDIO_TRACKS: HavenAudioTrack[] = [
  // --- 1. PIANO SOLO & LYRICAL PIANO MASTERPIECES ---
  {
    id: 'haven-piano-kiss-the-rain',
    title: 'Kiss the Rain',
    artist: 'Yiruma (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/yiruma-solo',
    durationSeconds: 256,
    src: '/audio/kiss-the-rain.mp3',
    weather: ['rain', 'clouds', 'dusk'],
    moods: ['reflective', 'calm', 'peaceful'],
    timeOfDay: ['day', 'dusk', 'night'],
    genreVi: 'Độc tấu Piano — Giai điệu mưa rơi trầm tư',
    category: 'piano',
  },
  {
    id: 'haven-piano-river-flows',
    title: 'River Flows in You',
    artist: 'Yiruma (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/yiruma-solo',
    durationSeconds: 218,
    src: '/audio/river-flows.mp3',
    weather: ['clear'],
    moods: ['hopeful', 'grateful', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Độc tấu Piano — Dòng sông hy vọng êm đềm',
    category: 'piano',
  },
  {
    id: 'haven-piano-spring-waltz',
    title: 'Spring Waltz',
    artist: 'Yiruma (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/yiruma-solo',
    durationSeconds: 236,
    src: '/audio/spring-waltz.mp3',
    weather: ['clear', 'clouds', 'dusk'],
    moods: ['calm', 'hopeful', 'peaceful'],
    timeOfDay: ['dawn', 'day', 'dusk'],
    genreVi: 'Độc tấu Piano — Bản Valse mùa xuân êm dịu',
    category: 'piano',
  },
  {
    id: 'haven-piano-destiny-of-love',
    title: 'Destiny of Love',
    artist: 'Yiruma (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/yiruma-solo',
    durationSeconds: 284,
    src: '/audio/destiny-of-love.mp3',
    weather: ['dusk', 'night', 'rain'],
    moods: ['reflective', 'grateful', 'peaceful'],
    timeOfDay: ['dusk', 'night'],
    genreVi: 'Độc tấu Piano — Định mệnh tình yêu da diết',
    category: 'piano',
  },
  {
    id: 'haven-piano-if-i-could-see-you-again',
    title: 'If I Could See You Again',
    artist: 'Yiruma (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/yiruma-solo',
    durationSeconds: 215,
    src: '/audio/if-i-could-see-you-again.mp3',
    weather: ['rain', 'clouds', 'fog'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['dusk', 'night'],
    genreVi: 'Độc tấu Piano — Hoài niệm sâu lắng',
    category: 'piano',
  },
  {
    id: 'haven-piano-shining-smile',
    title: 'Shining Smile',
    artist: 'Yiruma (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/yiruma-solo',
    durationSeconds: 228,
    src: '/audio/shining-smile.mp3',
    weather: ['clear', 'clouds'],
    moods: ['hopeful', 'grateful', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Độc tấu Piano — Nụ cười rạng rỡ ấm áp',
    category: 'piano',
  },
  {
    id: 'haven-piano-its-your-day',
    title: "It's Your Day",
    artist: 'Yiruma (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/yiruma-solo',
    durationSeconds: 224,
    src: '/audio/its-your-day.mp3',
    weather: ['clear', 'fog'],
    moods: ['grateful', 'peaceful', 'calm'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Độc tấu Piano — Ngày dịu dàng của bạn',
    category: 'piano',
  },
  {
    id: 'haven-piano-sometimes-someone',
    title: 'Sometimes Someone',
    artist: 'Yiruma (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/yiruma-solo',
    durationSeconds: 204,
    src: '/audio/sometimes-someone.mp3',
    weather: ['dusk', 'night', 'clouds'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['dusk', 'night'],
    genreVi: 'Độc tấu Piano — Khoảnh khắc ngóng trông hoài niệm',
    category: 'piano',
  },
  {
    id: 'haven-piano-joy',
    title: 'Joy',
    artist: 'Yiruma (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/yiruma-solo',
    durationSeconds: 216,
    src: '/audio/joy.mp3',
    weather: ['clear'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Độc tấu Piano — Niềm vui an nhiên thanh thản',
    category: 'piano',
  },
  {
    id: 'haven-piano-lost-in-island',
    title: 'Lost In Island',
    artist: 'Yiruma (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/yiruma-solo',
    durationSeconds: 209,
    src: '/audio/lost-in-island.mp3',
    weather: ['fog', 'clouds', 'rain'],
    moods: ['reflective', 'calm', 'peaceful'],
    timeOfDay: ['day', 'dusk'],
    genreVi: 'Độc tấu Piano — Lạc giữa đảo vắng an yên',
    category: 'piano',
  },
  {
    id: 'haven-piano-moonlight-sonata',
    title: 'Moonlight Sonata (Adagio)',
    artist: 'Ludwig van Beethoven (Acoustic Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/LudwigVanBeethovenMoonlightSonataAdagioSostenutogetTune.net',
    durationSeconds: 328,
    src: '/audio/moonlight-sonata.mp3',
    weather: ['night', 'dusk', 'fog'],
    moods: ['peaceful', 'calm', 'reflective'],
    timeOfDay: ['night', 'dusk'],
    genreVi: 'Độc tấu Piano — Ánh trăng huyền thoại trầm mặc',
    category: 'piano',
  },
  {
    id: 'haven-piano-chopin-nocturne-op9',
    title: 'Nocturne Op. 9 No. 2',
    artist: 'Frédéric Chopin (Acoustic Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/Chopin-NocturneOp.9No.2',
    durationSeconds: 249,
    src: '/audio/chopin-nocturne-op9.mp3',
    weather: ['night', 'dusk', 'clear'],
    moods: ['calm', 'reflective', 'peaceful'],
    timeOfDay: ['night', 'dusk', 'day'],
    genreVi: 'Độc tấu Piano — Dạ khúc lãng mạn thanh tao',
    category: 'piano',
  },
  {
    id: 'haven-piano-gymnopedie-no1',
    title: 'Gymnopédie No. 1',
    artist: 'Erik Satie (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/gymnopedie-1-erik-satie-176573_202506',
    durationSeconds: 235,
    src: '/audio/gymnopedie-no1.mp3',
    weather: ['fog', 'clouds', 'clear'],
    moods: ['calm', 'reflective', 'peaceful'],
    timeOfDay: ['dawn', 'day', 'night'],
    genreVi: 'Độc tấu Piano — Khúc Valse tĩnh lặng vô ưu',
    category: 'piano',
  },
  {
    id: 'haven-piano-gnossienne-no1',
    title: 'Gnossienne No. 1',
    artist: 'Erik Satie (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/erik-satie-gnossienne-no.-1',
    durationSeconds: 204,
    src: '/audio/gnossienne-no1.mp3',
    weather: ['fog', 'clouds', 'dusk'],
    moods: ['calm', 'reflective'],
    timeOfDay: ['dawn', 'day', 'night'],
    genreVi: 'Độc tấu Piano — Thiền ca phương Đông huyền bí',
    category: 'piano',
  },
  {
    id: 'haven-piano-clair-de-lune',
    title: 'Clair de Lune',
    artist: 'Claude Debussy (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/clair-de-lune_202408',
    durationSeconds: 280,
    src: '/audio/clair-de-lune.mp3',
    weather: ['night', 'dusk'],
    moods: ['peaceful', 'calm', 'grateful'],
    timeOfDay: ['night', 'dusk'],
    genreVi: 'Độc tấu Piano — Ánh trăng huyền ảo an yên',
    category: 'piano',
  },
  {
    id: 'haven-piano-bach-prelude-c',
    title: 'Prelude in C Major (BWV 846)',
    artist: 'J.S. Bach (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/BachWellTemperedKlavierBookI-PreludeInCMajor',
    durationSeconds: 141,
    src: '/audio/bach-prelude-c.mp3',
    weather: ['clear', 'fog'],
    moods: ['peaceful', 'hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Độc tấu Piano — Dạo đầu thanh khiết thuần khiết',
    category: 'piano',
  },
  {
    id: 'haven-piano-traumerei',
    title: 'Träumerei (Dreaming)',
    artist: 'Robert Schumann (Acoustic Grand Piano)',
    license: 'Public Domain / CC0',
    sourceUrl: 'https://archive.org/details/traumerei_202503',
    durationSeconds: 168,
    src: '/audio/traumerei.mp3',
    weather: ['dusk', 'night', 'clouds'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['dusk', 'night'],
    genreVi: 'Độc tấu Piano — Giấc mơ tuổi thơ ngọt ngào',
    category: 'piano',
  },

  // --- 2. AMBIENT SOUNDSCAPES & MEDITATION HARMONICS ---
  {
    id: 'haven-ambient-morning',
    title: 'Morning Mist',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/audio/morning-mist',
    durationSeconds: 180,
    src: '/audio/morning-mist.mp3',
    weather: ['fog', 'clear'],
    moods: ['calm', 'hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Âm hưởng sương sớm thanh khiết',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-rain-solace',
    title: 'Raindrop Solace',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/audio/rain-solace',
    durationSeconds: 210,
    src: '/audio/rain-solace.mp3',
    weather: ['rain', 'clouds'],
    moods: ['reflective', 'calm', 'peaceful'],
    timeOfDay: ['day', 'dusk', 'night'],
    genreVi: 'Tiếng mưa rơi an trú và suy ngẫm',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-solitude',
    title: 'Serene Solitude',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/audio/serene-solitude',
    durationSeconds: 210,
    src: '/audio/serene-solitude.mp3',
    weather: ['clouds', 'fog'],
    moods: ['reflective', 'peaceful', 'calm'],
    timeOfDay: ['day', 'dusk'],
    genreVi: 'Khoảng lặng chiêm nghiệm nội tâm',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-ocean-whispers',
    title: 'Ocean Whispers',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/audio/ocean-whispers',
    durationSeconds: 210,
    src: '/audio/ocean-whispers.mp3',
    weather: ['clear', 'clouds', 'dusk'],
    moods: ['peaceful', 'calm', 'reflective'],
    timeOfDay: ['day', 'dusk', 'night'],
    genreVi: 'Tiếng sóng vỗ bờ cát ru dịu tâm hồn',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-forest-canopy',
    title: 'Forest Canopy',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/audio/forest-canopy',
    durationSeconds: 210,
    src: '/audio/forest-canopy.mp3',
    weather: ['fog', 'clouds', 'clear'],
    moods: ['calm', 'peaceful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Gió lùa vòm lá rừng già thanh tịnh',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-golden-dusk',
    title: 'Golden Dusk',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/audio/golden-dusk',
    durationSeconds: 210,
    src: '/audio/golden-dusk.mp3',
    weather: ['dusk', 'clear'],
    moods: ['grateful', 'peaceful', 'reflective'],
    timeOfDay: ['dusk'],
    genreVi: 'Giai điệu ráng chiều ấm áp',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-starlight-lullaby',
    title: 'Starlight Lullaby',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/audio/starlight-lullaby',
    durationSeconds: 210,
    src: '/audio/starlight-lullaby.mp3',
    weather: ['night'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['night'],
    genreVi: 'Ngân hà ru đêm tĩnh mịch ngàn sao',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-nightfall',
    title: 'Gentle Nightfall',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/audio/gentle-nightfall',
    durationSeconds: 240,
    src: '/audio/gentle-nightfall.mp3',
    weather: ['night'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['night'],
    genreVi: 'Khúc ru đêm tĩnh mịch an giấc',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-zen-garden',
    title: 'Zen Garden',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/audio/zen-garden',
    durationSeconds: 210,
    src: '/audio/zen-garden.mp3',
    weather: ['clear', 'clouds', 'fog'],
    moods: ['peaceful', 'calm', 'grateful'],
    timeOfDay: ['day', 'dawn'],
    genreVi: 'Vườn thiền chuông ngân thanh tịnh',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-hopeful-dawn',
    title: 'Hopeful Dawn',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/audio/hopeful-dawn',
    durationSeconds: 210,
    src: '/audio/hopeful-dawn.mp3',
    weather: ['clear'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Bình minh hé rạng ngập tràn hy vọng',
    category: 'ambient',
  },
];

export function getPianoTracks(): HavenAudioTrack[] {
  return ALL_HAVEN_AUDIO_TRACKS.filter((t) => t.category === 'piano');
}

export function getAmbientTracks(): HavenAudioTrack[] {
  return ALL_HAVEN_AUDIO_TRACKS.filter((t) => t.category === 'ambient');
}

export function getAllHavenAudioTracks(): HavenAudioTrack[] {
  return [...ALL_HAVEN_AUDIO_TRACKS];
}

export function getDefaultHavenAudioTrack(): HavenAudioTrack {
  return ALL_HAVEN_AUDIO_TRACKS[0];
}
