import type { AudioTrack } from './tracks';
import { DEFAULT_TRACKS } from './tracks';
import type { WeatherCondition, TimeOfDay } from '../weather/weather';

export interface HavenAudioTrack extends AudioTrack {
  weather: WeatherCondition[];
  moods: string[];
  timeOfDay: TimeOfDay[];
  genreVi: string;
  category: 'piano' | 'ambient';
}

/**
 * Curated Haven Art Ambient & Classical Piano Catalog
 * Expanded collection of serene ambient soundscapes and soulful acoustic piano masterpieces.
 */
export const ALL_HAVEN_AUDIO_TRACKS: HavenAudioTrack[] = [
  // --- 1. PIANO SOLO & LYRICAL PIANO MASTERPIECES ---
  {
    id: 'haven-piano-original-01',
    title: 'Quiet Rain',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-01.mp3',
    weather: ['rain', 'clouds', 'dusk'],
    moods: ['reflective', 'calm', 'peaceful'],
    timeOfDay: ['day', 'dusk', 'night'],
    genreVi: 'Piano tổng hợp nguyên bản — Quiet Rain',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-02',
    title: 'Riverlight',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-02.mp3',
    weather: ['clear'],
    moods: ['hopeful', 'grateful', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Piano tổng hợp nguyên bản — Riverlight',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-03',
    title: 'Spring Air',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-03.mp3',
    weather: ['clear', 'clouds', 'dusk'],
    moods: ['calm', 'hopeful', 'peaceful'],
    timeOfDay: ['dawn', 'day', 'dusk'],
    genreVi: 'Piano tổng hợp nguyên bản — Spring Air',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-04',
    title: 'Evening Letters',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-04.mp3',
    weather: ['dusk', 'night', 'rain'],
    moods: ['reflective', 'grateful', 'peaceful'],
    timeOfDay: ['dusk', 'night'],
    genreVi: 'Piano tổng hợp nguyên bản — Evening Letters',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-05',
    title: 'Soft Memory',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-05.mp3',
    weather: ['rain', 'clouds', 'fog'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['dusk', 'night'],
    genreVi: 'Piano tổng hợp nguyên bản — Soft Memory',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-06',
    title: 'First Light',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-06.mp3',
    weather: ['clear', 'clouds'],
    moods: ['hopeful', 'grateful', 'peaceful'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Piano tổng hợp nguyên bản — First Light',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-07',
    title: 'A Gentle Day',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-07.mp3',
    weather: ['clear', 'fog'],
    moods: ['grateful', 'peaceful', 'calm'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Piano tổng hợp nguyên bản — A Gentle Day',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-08',
    title: 'Stillness',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-08.mp3',
    weather: ['dusk', 'night', 'clouds'],
    moods: ['reflective', 'calm'],
    timeOfDay: ['dusk', 'night'],
    genreVi: 'Piano tổng hợp nguyên bản — Stillness',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-09',
    title: 'Dawn Echo',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-09.mp3',
    weather: ['clear'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Piano tổng hợp nguyên bản — Dawn Echo',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-10',
    title: 'Moonlit Room',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-10.mp3',
    weather: ['fog', 'clouds', 'rain'],
    moods: ['reflective', 'calm', 'peaceful'],
    timeOfDay: ['day', 'dusk'],
    genreVi: 'Piano tổng hợp nguyên bản — Moonlit Room',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-11',
    title: 'Pale Clouds',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-11.mp3',
    weather: ['night', 'dusk', 'fog'],
    moods: ['peaceful', 'calm', 'reflective'],
    timeOfDay: ['night', 'dusk'],
    genreVi: 'Piano tổng hợp nguyên bản — Pale Clouds',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-12',
    title: 'Open Window',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-12.mp3',
    weather: ['night', 'dusk', 'clear'],
    moods: ['calm', 'reflective', 'peaceful'],
    timeOfDay: ['night', 'dusk', 'day'],
    genreVi: 'Piano tổng hợp nguyên bản — Open Window',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-13',
    title: 'Slow Morning',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-13.mp3',
    weather: ['fog', 'clouds', 'clear'],
    moods: ['calm', 'reflective', 'peaceful'],
    timeOfDay: ['dawn', 'day', 'night'],
    genreVi: 'Piano tổng hợp nguyên bản — Slow Morning',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-14',
    title: 'Night Walk',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-14.mp3',
    weather: ['fog', 'clouds', 'dusk'],
    moods: ['calm', 'reflective'],
    timeOfDay: ['dawn', 'day', 'night'],
    genreVi: 'Piano tổng hợp nguyên bản — Night Walk',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-15',
    title: 'Warm Hearth',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-15.mp3',
    weather: ['night', 'dusk'],
    moods: ['peaceful', 'calm', 'grateful'],
    timeOfDay: ['night', 'dusk'],
    genreVi: 'Piano tổng hợp nguyên bản — Warm Hearth',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-16',
    title: 'Garden Notes',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-16.mp3',
    weather: ['clear', 'fog'],
    moods: ['peaceful', 'hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Piano tổng hợp nguyên bản — Garden Notes',
    category: 'piano',
  },
  {
    id: 'haven-piano-original-17',
    title: 'Restful Sky',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/original-piano-17.mp3',
    weather: ['dusk', 'night', 'clouds'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['dusk', 'night'],
    genreVi: 'Piano tổng hợp nguyên bản — Restful Sky',
    category: 'piano',
  },

  // --- 2. AMBIENT SOUNDSCAPES & MEDITATION HARMONICS ---
  {
    id: 'haven-ambient-morning',
    title: 'Morning Mist',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/morning-mist.mp3',
    weather: ['fog', 'clear'],
    moods: ['calm', 'hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Âm hưởng sương sớm thanh khiết',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-rain-solace',
    title: 'Raindrop Solace',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/rain-solace.mp3',
    weather: ['rain', 'clouds'],
    moods: ['reflective', 'calm', 'peaceful'],
    timeOfDay: ['day', 'dusk', 'night'],
    genreVi: 'Tiếng mưa rơi an trú và suy ngẫm',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-solitude',
    title: 'Serene Solitude',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/serene-solitude.mp3',
    weather: ['clouds', 'fog'],
    moods: ['reflective', 'peaceful', 'calm'],
    timeOfDay: ['day', 'dusk'],
    genreVi: 'Khoảng lặng chiêm nghiệm nội tâm',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-ocean-whispers',
    title: 'Ocean Whispers',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/ocean-whispers.mp3',
    weather: ['clear', 'clouds', 'dusk'],
    moods: ['peaceful', 'calm', 'reflective'],
    timeOfDay: ['day', 'dusk', 'night'],
    genreVi: 'Tiếng sóng vỗ bờ cát ru dịu tâm hồn',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-forest-canopy',
    title: 'Forest Canopy',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/forest-canopy.mp3',
    weather: ['fog', 'clouds', 'clear'],
    moods: ['calm', 'peaceful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Gió lùa vòm lá rừng già thanh tịnh',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-golden-dusk',
    title: 'Golden Dusk',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/golden-dusk.mp3',
    weather: ['dusk', 'clear'],
    moods: ['grateful', 'peaceful', 'reflective'],
    timeOfDay: ['dusk'],
    genreVi: 'Giai điệu ráng chiều ấm áp',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-starlight-lullaby',
    title: 'Starlight Lullaby',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/starlight-lullaby.mp3',
    weather: ['night'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['night'],
    genreVi: 'Ngân hà ru đêm tĩnh mịch ngàn sao',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-nightfall',
    title: 'Gentle Nightfall',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/gentle-nightfall.mp3',
    weather: ['night'],
    moods: ['calm', 'peaceful', 'reflective'],
    timeOfDay: ['night'],
    genreVi: 'Khúc ru đêm tĩnh mịch an giấc',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-zen-garden',
    title: 'Zen Garden',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/zen-garden.mp3',
    weather: ['clear', 'clouds', 'fog'],
    moods: ['peaceful', 'calm', 'grateful'],
    timeOfDay: ['day', 'dawn'],
    genreVi: 'Vườn thiền chuông ngân thanh tịnh',
    category: 'ambient',
  },
  {
    id: 'haven-ambient-hopeful-dawn',
    title: 'Hopeful Dawn',
    artist: 'Haven Soundscapes',
    license: 'CC0 1.0 Universal / Public Domain',
    sourceUrl: 'https://havenart.space/media-provenance',
    durationSeconds: 36,
    src: '/audio/hopeful-dawn.mp3',
    weather: ['clear'],
    moods: ['hopeful', 'grateful'],
    timeOfDay: ['dawn', 'day'],
    genreVi: 'Bình minh hé rạng ngập tràn hy vọng',
    category: 'ambient',
  },
];

export function getPianoTracks(): HavenAudioTrack[] {
  return ALL_HAVEN_AUDIO_TRACKS.filter((t) => t.category === 'piano');
}

export function getAmbientTracks(): HavenAudioTrack[] {
  return ALL_HAVEN_AUDIO_TRACKS.filter((t) => t.category === 'ambient');
}

export function getAllHavenAudioTracks(): HavenAudioTrack[] {
  return [...ALL_HAVEN_AUDIO_TRACKS];
}

export function getDefaultHavenAudioTrack(): HavenAudioTrack {
  return ALL_HAVEN_AUDIO_TRACKS[0];
}
